name: Build and Test

on:
  push:
    branches:
      - citests
  pull_request:
    branches:
      - citests

jobs:
  macos-python-clang:
    name: tests macos with python and clang
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: install numpy
      run: pip3 install numpy scipy
    - name: create_build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON=ON ..
      working-directory: build
      env:
        CC: clang
        CXX: clang++
    - name: make
      run: make -j2
      working-directory: build
    - name: test
      run: make test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        CTEST_PARALLEL_LEVEL: 2
      working-directory: build

  # windows-python-clang:
  #   name: tests windows with python and clang
  #   runs-on: [windows-latest]
  #
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: create_build
  #     run: mkdir build
  #   - name: cmake
  #     run: cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON=ON ..
  #     working-directory: build
  #     env:
  #       CC: clang
  #       CXX: clang++
  #   - name: build
  #     run: cmake --build .
  #     env:
  #       CMAKE_BUILD_PARALLEL_LEVEL: 2
  #     working-directory: build
  #   - name: test
  #     run: ctest
  #     env:
  #       CTEST_OUTPUT_ON_FAILURE: 1
  #       CTEST_PARALLEL_LEVEL: 2
  #     working-directory: build

  ubuntu-python-openmp:
    name: tests ubuntu with python and openmp and gcc 10
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: prereqs
      run: sudo apt-get install python3-numpy python3-scipy
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: create_build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DOPENMP=ON -DPYTHON=ON ..
      working-directory: build
      env:
        CC: gcc-10
        CXX: g++-10
    - name: make
      run: make -j2
      working-directory: build
    - name: test
      run: make test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        CTEST_PARALLEL_LEVEL: 2
      working-directory: build

  ubuntu-python-openmp-clang:
    name: tests ubuntu with python and openmp and clang 11
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: prereqs
      run: sudo apt-get install python3-numpy python3-scipy
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: create_build
      run: mkdir build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DOPENMP=ON -DPYTHON=ON ..
      working-directory: build
      env:
        CC: clang-11
        CXX: clang++-11
    - name: make
      run: make -j2
      working-directory: build
    - name: test
      run: make test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        CTEST_PARALLEL_LEVEL: 2
      working-directory: build
